server:
  port: 8081

spring:
  profiles:
    active: dev
    include: swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  datasource:
    url: jdbc:postgresql://localhost:5432/mma_2
    username: docker
    password: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace
